.TH BASICTOOL 1 "July 2021" "basictool 0.05" "User Commands"
.SH NAME
basictool \- tokenise, de-tokenise, pack, unpack and analyse BBC BASIC programs
.SH SYNOPSIS
.B basictool
[\fI\,OPTION\/\fR]... INPUTFILE [\fI\,OUTPUTFILE\/\fR]
.SH DESCRIPTION
basictool can convert BBC BASIC programs between ASCII text and the tokenised form used by (6502) BBC BASIC. It can also pack programs (making them shorter but less readable), unpack them (to partially reverse the effects of packing) and generate variable and line number references. Behind the scenes, it is really a specialised BBC Micro emulator which uses the BBC BASIC and Advanced BASIC Editor ROMs to operate on BBC BASIC programs.

basictool expects at least one argument, the name of the input file. The input may be either tokenised or ASCII BBC BASIC; basictool will auto-detect the type of input, although this can be overridden using
.B --input-tokenised
if necessary. To read from standard input, specify the input file as
.B -
\&. A second argument, the name of the output file, may be given; if this isn't specified, standard output will be used.
.SH OPTIONS
TODO!
.SH EXAMPLES
.PP
Tokenise an ASCII BASIC program so it can be loaded by BBC BASIC.
.br
\fI$ basictool -t prog.txt prog.tok\fR
.br
.PP
Display a tokenised BASIC program as human-readable ASCII.
.br
\fI$ basictool prog.tok\fR
.PP
Tokenise and pack an ASCII BASIC program so it can be loaded by BBC BASIC and use less memory.
.br
\fI$ basictool -t -p prog.txt prog.tok\fR
.\" TODO: more?
